// ARSENIOR-RENT/ProyectoFigma/components/CarCatalog.tsx
import React, { useState } from 'react';
import { ArrowLeft, Star, Users, Fuel, Settings, Shield, Crown, Filter } from 'lucide-react';
import { Button } from './ui/button';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Car, User } from '../App';

interface CarCatalogProps {
  cars: Car[];
  onViewCar: (car: Car) => void;
  onBack: () => void;
  currentUser: User | null;
  onShowAuth: () => void;
}

export function CarCatalog({ cars, onViewCar, onBack, currentUser, onShowAuth }: CarCatalogProps) {
  const [sortBy, setSortBy] = useState('recommended');
  const [filterBy, setFilterBy] = useState('all');

  const getStatusBadge = (status: Car['status']) => {
    switch (status) {
      case 'available':
        return <Badge className="bg-emerald-100 text-emerald-700 border-emerald-200">Disponible</Badge>;
      case 'rented':
        return <Badge className="bg-amber-100 text-amber-700 border-amber-200">Rentado</Badge>;
      case 'maintenance':
        return <Badge className="bg-red-100 text-red-700 border-red-200">Mantenimiento</Badge>;
      default:
        return null;
    }
  };

  const filteredCars = cars.filter(car => {
    if (filterBy === 'all') return true;
    return car.status === filterBy;
  });

  const sortedCars = [...filteredCars].sort((a, b) => {
    switch (sortBy) {
      case 'price-low':
        return a.pricePerDay - b.pricePerDay;
      case 'price-high':
        return b.pricePerDay - a.pricePerDay;
      case 'rating':
        return b.rating - a.rating;
      default:
        return 0;
    }
  });

  return (
    <div className="min-h-screen bg-gradient-to-br from-stone-50 via-stone-100 to-amber-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-lg border-b border-stone-200/50 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center space-x-4">
              <button
                onClick={onBack}
                className="p-2 hover:bg-stone-100 rounded-lg transition-colors"
              >
                <ArrowLeft size={20} className="text-stone-600" />
              </button>
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-r from-amber-600 to-amber-700 rounded-lg flex items-center justify-center">
                  <span className="text-white font-serif text-sm">A</span>
                </div>
                <span className="font-serif text-xl text-stone-900">Arsenior Rent</span>
              </div>
            </div>

            <div className="flex items-center space-x-3">
              {currentUser ? (
                <span className="text-stone-700 text-sm">Hola, {currentUser.name}</span>
              ) : (
                <Button variant="outline" size="sm" onClick={onShowAuth}>
                  Iniciar Sesión
                </Button>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Page Title */}
      <section className="py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-8">
            <h1 className="font-serif text-3xl md:text-4xl text-stone-900 mb-4">
              Nuestra Flota Premium
            </h1>
            <p className="text-stone-600 text-lg max-w-2xl mx-auto">
              Vehículos cuidadosamente seleccionados para ofrecerte la mejor experiencia de manejo
            </p>
          </div>

          {/* Filters & Sorting */}
          <div className="flex flex-col md:flex-row gap-4 mb-8">
            <div className="flex items-center space-x-2">
              <Filter size={18} className="text-stone-600" />
              <Select value={filterBy} onValueChange={setFilterBy}>
                <SelectTrigger className="w-48 bg-white/50 border-stone-200">
                  <SelectValue placeholder="Filtrar por estado" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Todos los vehículos</SelectItem>
                  <SelectItem value="available">Disponibles</SelectItem>
                  <SelectItem value="rented">Rentados</SelectItem>
                  <SelectItem value="maintenance">En mantenimiento</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center space-x-2">
              <Settings size={18} className="text-stone-600" />
              <Select value={sortBy} onValueChange={setSortBy}>
                <SelectTrigger className="w-48 bg-white/50 border-stone-200">
                  <SelectValue placeholder="Ordenar por" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="recommended">Recomendados</SelectItem>
                  <SelectItem value="price-low">Precio: Menor a Mayor</SelectItem>
                  <SelectItem value="price-high">Precio: Mayor a Menor</SelectItem>
                  <SelectItem value="rating">Mejor Calificados</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
      </section>

      {/* Cars Grid */}
      <section className="pb-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {sortedCars.map((car) => (
              <Card key={car.id} className="overflow-hidden bg-white/60 backdrop-blur-sm border-stone-200/50 shadow-xl hover:shadow-2xl transition-all duration-300 group">
                {/* Car Image */}
                <div className="relative aspect-[4/3] overflow-hidden">
                  <img
                    src={car.image}
                    alt={`${car.brand} ${car.model}`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute top-3 left-3">
                    {getStatusBadge(car.status)}
                  </div>
                  <div className="absolute top-3 right-3">
                    <div className="bg-white/90 backdrop-blur-sm rounded-full px-2 py-1 flex items-center space-x-1">
                      <Star size={14} className="text-amber-500 fill-current" />
                      <span className="text-sm text-stone-700">{car.rating}</span>
                    </div>
                  </div>
                </div>

                {/* Car Info */}
                <div className="p-6">
                  <div className="mb-4">
                    <h3 className="font-serif text-xl text-stone-900 mb-1">
                      {car.brand} {car.model}
                    </h3>
                    <p className="text-stone-600 text-sm">{car.type} • {car.year}</p>
                  </div>

                  {/* Features */}
                  <div className="grid grid-cols-2 gap-3 mb-4 text-sm text-stone-600">
                    <div className="flex items-center space-x-2">
                      <Users size={14} className="text-amber-700" />
                      <span>{car.seats} asientos</span>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Settings size={14} className="text-amber-700" />
                      <span>{car.transmission}</span>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Fuel size={14} className="text-amber-700" />
                      <span>{car.fuel}</span>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Star size={14} className="text-amber-700" />
                      <span>{car.reviews} reseñas</span>
                    </div>
                  </div>

                  {/* Plans */}
                  <div className="space-y-3 mb-6">
                    <div className="flex items-center justify-between p-3 bg-stone-50 rounded-lg border border-stone-200">
                      <div className="flex items-center space-x-2">
                        <Shield size={16} className="text-stone-600" />
                        <span className="text-sm text-stone-700">Plan Base</span>
                      </div>
                      <span className="text-stone-900">${car.pricePerDay.toLocaleString()}/día</span>
                    </div>
                    
                    <div className="flex items-center justify-between p-3 bg-gradient-to-r from-amber-50 to-amber-100 rounded-lg border border-amber-200">
                      <div className="flex items-center space-x-2">
                        <Crown size={16} className="text-amber-700" />
                        <span className="text-sm text-amber-700">Plan Premier</span>
                      </div>
                      <span className="text-amber-800">${(car.pricePerDay * 1.3).toLocaleString()}/día</span>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="space-y-2">
                    <Button
                      onClick={() => onViewCar(car)}
                      disabled={car.status !== 'available'}
                      className="w-full bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-700 hover:to-amber-800 text-white transition-all duration-300 disabled:from-stone-300 disabled:to-stone-400"
                    >
                      {car.status === 'available' ? 'Ver Detalles' : 'No Disponible'}
                    </Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>

          {sortedCars.length === 0 && (
            <div className="text-center py-16">
              <div className="w-16 h-16 bg-stone-200 rounded-full mx-auto mb-4 flex items-center justify-center">
                <Settings size={24} className="text-stone-500" />
              </div>
              <h3 className="text-lg text-stone-900 mb-2">No se encontraron vehículos</h3>
              <p className="text-stone-600">Prueba ajustando los filtros de búsqueda</p>
            </div>
          )}
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="bg-stone-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="font-serif text-2xl md:text-3xl mb-4">
            ¿Necesitas Ayuda para Elegir?
          </h2>
          <p className="text-stone-300 mb-6 leading-relaxed">
            Nuestro equipo de expertos está disponible 24/7 para ayudarte a encontrar el vehículo perfecto para tu viaje.
          </p>
          <Button
            variant="outline"
            className="bg-transparent border-white text-white hover:bg-white hover:text-stone-900"
          >
            Contactar Asesor
          </Button>
        </div>
      </section>
    </div>
  );
}

// ARSENIOR-RENT/frontend/src/app/components/car-catalog/car-catalog/car-catalog.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CarsService } from '../../../services/cars.service';
import { NavbarComponent } from '../../shared/navbar/navbar/navbar.component';
import { FooterComponent } from '../../shared/footer/footer/footer.component';
import { LoadingSpinnerComponent } from '../../shared/loading-spinner/loading-spinner/loading-spinner.component';
import { Car, CarFilters } from '../../../models/car.model';

@Component({
  selector: 'app-car-catalog',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    NavbarComponent,
    FooterComponent,
    LoadingSpinnerComponent
  ],
  templateUrl: './car-catalog.component.html',
  styleUrls: ['./car-catalog.component.css']
})
export class CarCatalogComponent implements OnInit {
  cars = signal<Car[]>([]);
  filteredCars = signal<Car[]>([]);
  loading = signal(true);
  error = signal('');

  // Filtros
  filters: CarFilters = {
    segment: undefined,
    transmission: undefined,
    minSeats: undefined
  };

  selectedSegment = '';
  selectedTransmission = '';
  selectedSeats = '';

  constructor(private carsService: CarsService) {}

  ngOnInit(): void {
    this.loadCars();
  }

  loadCars(): void {
    this.loading.set(true);
    this.carsService.getAllCars().subscribe({
      next: (data) => {
        this.cars.set(data);
        this.filteredCars.set(data);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set('Error al cargar el catálogo');
        this.loading.set(false);
      }
    });
  }

  applyFilters(): void {
    let filtered = this.cars();

    if (this.selectedSegment) {
      filtered = filtered.filter(car => car.segment === this.selectedSegment);
    }

    if (this.selectedTransmission) {
      filtered = filtered.filter(car => car.transmission === this.selectedTransmission);
    }

    if (this.selectedSeats) {
      const minSeats = parseInt(this.selectedSeats);
      filtered = filtered.filter(car => car.seats >= minSeats);
    }

    this.filteredCars.set(filtered);
  }

  clearFilters(): void {
    this.selectedSegment = '';
    this.selectedTransmission = '';
    this.selectedSeats = '';
    this.filteredCars.set(this.cars());
  }

  getSegmentLabel(segment: string): string {
    const labels: { [key: string]: string } = {
      'A': 'Premium',
      'B': 'Standard',
      'C': 'Basic'
    };
    return labels[segment] || segment;
  }

  getStarRating(rating: number): string[] {
    const stars = [];
    for (let i = 0; i < 5; i++) {
      stars.push(i < Math.round(rating) ? '★' : '☆');
    }
    return stars;
  }
}
<app-navbar></app-navbar>

<main class="min-h-screen bg-gray-50">
  
  <!-- Header -->
  <section class="bg-white border-b border-gray-200 py-12">
    <div class="container-custom">
      <h1 class="font-playfair text-center mb-4">Nuestro Catálogo</h1>
      <div class="divider"></div>
      <p class="text-center text-gray-600 max-w-2xl mx-auto">
        Explora nuestra selección de vehículos premium. Cada uno mantenido con los más altos estándares de calidad.
      </p>
    </div>
  </section>

  <!-- Filters -->
  <section class="bg-white border-b border-gray-200 py-6">
    <div class="container-custom">
      <div class="flex flex-col md:flex-row gap-4 items-end">
        
        <!-- Segment Filter -->
        <div class="flex-1">
          <label for="segment" class="text-xs">Categoría</label>
          <select
            id="segment"
            [(ngModel)]="selectedSegment"
            (change)="applyFilters()"
            class="w-full"
          >
            <option value="">Todas</option>
            <option value="A">Premium (A)</option>
            <option value="B">Standard (B)</option>
            <option value="C">Basic (C)</option>
          </select>
        </div>

        <!-- Transmission Filter -->
        <div class="flex-1">
          <label for="transmission" class="text-xs">Transmisión</label>
          <select
            id="transmission"
            [(ngModel)]="selectedTransmission"
            (change)="applyFilters()"
            class="w-full"
          >
            <option value="">Todas</option>
            <option value="Automática">Automática</option>
            <option value="Manual">Manual</option>
          </select>
        </div>

        <!-- Seats Filter -->
        <div class="flex-1">
          <label for="seats" class="text-xs">Asientos Mínimos</label>
          <select
            id="seats"
            [(ngModel)]="selectedSeats"
            (change)="applyFilters()"
            class="w-full"
          >
            <option value="">Todos</option>
            <option value="2">2+</option>
            <option value="4">4+</option>
            <option value="5">5+</option>
            <option value="7">7+</option>
          </select>
        </div>

        <!-- Clear Button -->
        <button (click)="clearFilters()" class="btn-ghost">
          Limpiar Filtros
        </button>
      </div>
    </div>
  </section>

  <!-- Cars Grid -->
  <section class="section-padding">
    <div class="container-custom">
      
      @if (loading()) {
        <app-loading-spinner [size]="300" message="Cargando catálogo..."></app-loading-spinner>
      }

      @if (error()) {
        <div class="error-message text-center">
          {{ error() }}
        </div>
      }

      @if (!loading() && filteredCars().length === 0) {
        <div class="text-center py-16">
          <p class="text-gray-600 text-lg">No se encontraron vehículos con los filtros seleccionados.</p>
          <button (click)="clearFilters()" class="btn-primary mt-6">
            Ver Todos los Vehículos
          </button>
        </div>
      }

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        @for (car of filteredCars(); track car.id) {
          <div class="card group cursor-pointer" [routerLink]="['/car', car.id]">
            
            <!-- Image -->
            <div class="aspect-[4/3] bg-gray-200 mb-4 overflow-hidden">
              @if (car.image) {
                <img [src]="car.image" [alt]="car.brand + ' ' + car.model" 
                     class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
              } @else {
                <div class="w-full h-full flex items-center justify-center text-gray-400">
                  Sin imagen
                </div>
              }
            </div>

            <!-- Segment Badge -->
            <div class="mb-3">
              <span class="badge">{{ getSegmentLabel(car.segment) }}</span>
            </div>

            <!-- Title -->
            <h3 class="font-playfair mb-2">{{ car.brand }} {{ car.model }}</h3>
            <p class="text-sm text-gray-600 mb-4">{{ car.year }}</p>

            <!-- Rating -->
            <div class="flex items-center gap-1 mb-4">
              @for (star of getStarRating(car.rating); track $index) {
                <span class="text-black">{{ star }}</span>
              }
              <span class="text-sm text-gray-600 ml-2">
                ({{ car.totalRatings }} reseñas)
              </span>
            </div>

            <!-- Features -->
            <div class="flex items-center gap-4 text-sm text-gray-600 mb-4">
              <span>{{ car.transmission }}</span>
              <span>•</span>
              <span>{{ car.seats }} asientos</span>
              <span>•</span>
              <span>{{ car.fuelType }}</span>
            </div>

            <!-- Price -->
            <div class="border-t border-gray-200 pt-4">
              <p class="text-2xl font-playfair">${{ car.pricePerDay }}<span class="text-sm text-gray-600">/día</span></p>
            </div>

            <!-- Status -->
            @if (car.status !== 'disponible') {
              <div class="mt-3">
                <span class="badge badge-warning">
                  {{ car.status === 'rentado' ? 'Rentado' : 'Mantenimiento' }}
                </span>
              </div>
            }
          </div>
        }
      </div>
    </div>
  </section>
</main>

<app-footer></app-footer>
